apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: dvop-srv-consult-product

resources:
- deployment.yaml
- service.yaml

images:
  - name: dvop-srv-consult-product
    newName: alexsouzasilva/dvop-srv-consult-product
    newTag: latest
