name: Build and Deploy
on: 
    push:
        branches:
            - main
            - develop
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warging'
                type: choice
                options:
                    - info
                    - warning
                    - debug

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Print a greeting
              env:
                MY_VAR: Hi, there! My name is
                FIRST_NAME: Alex
                LAST_NAME: Silva
              run: |
                echo  $MY_VAR $FIRST_NAME $LAST_NAME.


