name: Build and Deploy
run-name: Executado by ${{ github.actor }}
on: 
    push:
        branches:
            - main
            - develop
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warging'
                type: choice
                options:
                    - info
                    - warning
                    - debug

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Print a greeting
              env:
                MY_VAR: Hi, there! My name is
                FIRST_NAME: Alex
                LAST_NAME: Silva
              run: |
                echo  $MY_VAR $FIRST_NAME $LAST_NAME.
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: 'maven'
            - name: Run the Maven
              run: mvn clean install
            - name: Run Maven Test
              run: mvn test

    Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Kustomize Build
              uses: karancode/kustomize-github-action@master
              with:
                kustomize_version: 'v5.3.0'
                kustomize_build_dir: '/k8s'
                kustomize_comment: true
                kustomize_output_file: "k8s/rendered.yaml"
                kustomize_build_options: "--load_restrictor none"
                enable_alpha_plugins: true
              env:
                GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}    






