name: Build and Deploy
run-name: Executado by ${{ github.actor }}
on: 
    push:
        branches:
            - main
            - develop
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warging'
                type: choice
                options:
                    - info
                    - warning
                    - debug

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Print a greeting
              env:
                MY_VAR: Hi, there! My name is
                FIRST_NAME: Alex
                LAST_NAME: Silva

              run: |
                echo  $MY_VAR $FIRST_NAME $LAST_NAME.
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: 'maven'
            - name: Run the Maven
              run: mvn clean install

    call-reusable-workflow:
        needs: Build
        uses: alexdesouzasilva/reusables/.github/workflows/docker.yaml@main
        with:
            username: alexsouzasilva
            version: ${{ github.sha }}
        secrets:
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            

    call-reusable-workflow2:
        needs: Build
        uses: alexdesouzasilva/reusables/.github/workflows/kustomize.yaml@main
        with:
            version: ${{ github.sha }}









